### Multiplying 0's and 1's - Proofs {.unnumbered}

In this example, we introduce a proof system $\mathbf{T}$ by which to reason in the language $L_\times$ introduced in @exm-0x1-syntax.

The proof system $\mathbf{T}$ has three axioms:
$$
x = x \quad\quad\quad 0 = 0 \quad\quad\quad 1 = 1
$$

In addition, the system $\mathbf{T}$ has ten rules of inference.
The first four of these rules concern the addition and removal of the numerals $1$ and $0$ from numerical expressions (here, $\alpha$, $\beta$, and $\gamma$ are any numerical expressions):

(1$-$):
$$
\frac{1\times \alpha = \beta}{\alpha=\beta}
$$

(1+):
$$
\frac{\alpha = \beta}{1\times\alpha=\beta}
$$

(0$-$):
$$
\frac{0\times\alpha = \beta}{0 =\beta}
$$

(0+):
$$
\frac{0 = \alpha}{0\times\beta = \alpha}
$$

The next two rules concern the addition and removal of the numeral $x$ from numerical expressions:

($x-$): If $x$ occurs in $\alpha$, then:
$$
\frac{x\times \alpha = \beta}{\alpha = \beta}
$$

($x+$): If $x$ occurs in $\alpha$, then:
$$
\frac{\alpha = \beta}{x\times \alpha = \beta}
$$

The seventh rule expresses that the equality relation is symmetrical:

(S):
$$
\frac{\alpha = \beta}{\beta = \alpha}
$$

and the eighth, that it is transitive:

(T):
$$
\frac{\alpha = \beta\quad\beta=\gamma}{\alpha = \gamma}
$$

The ninth rule asserts that from $0 = 1$, any sentence $\ph$ follows:

($\neq$):
$$
\frac{0 = 1}{\ph}
$$

The tenth and final rule expresses the symmetricality of the operator $\times$:

($\times$):
$$
\frac{\alpha\times\beta = \gamma}{\beta\times\alpha = \gamma}
$$

As an illustration of reasoning in the proof system $\mathbf{T}$, we will show that:
$$
x\times 0 = 0\times 1,\quad 1\times x \times 1 = 1 \proves_{\mathbf{T}} 1 = x
$$

The proof is as follows:

:::{.lproof}
    1. 1 \times x \times 1 = 1  [Premise]
    2. x \times 1 = 1           [1$-$: 1]
    3. 1\times x = 1            [$\times$: 2]
    4. x = 1                    [1$-$: 3]
    5. 1 = x                    [S: 4]
:::
