---
bibliography: "propositional-logic.bib"
number-sections: true
crossref: 
    chapters: true
---

{{< include /assets/macros/macros.qmd >}}

# Propositional Logic {#sec-propositional-logic .chapter}

## Introduction {#sec-propositional-logic-introduction}

Propositional logic is the study of the inferential relations that obtain between compound propositions that are built up from other more simple propositions through the application of various logical operations.
The specific system of propositional logic that we will study in this chapter will focus on a particular kind of proposition forming operation, namely, that which yields a compound proposition the truth value of which is a function of the truth values of the component propositions from which it is constructed.
Such operations are all called 'truth-functional' operations, or, 'Boolean' operations, for short.[^Boole]

[^Boole]: The label 'Boolean' is in honor of the English mathematician George Boole, whose seminal work, _An Investigation of the Laws of Thought_ [-@Boole1854-ur], layed the foundation for the branch of mathematics now called Boolean algebra.
In the examples given in this chapter, we will explain, in more detail, how Boolean algebra can be view as a system of propositional logic.

Truth-functional, or Boolean, propositional logic forms the core of most other systems of logic utilized in philosophical analysis, including first-order predicate logic and modal logic.[^classical] It also provides the standard context in which the theory of probability is developed.
It thus constitutes the first essential entry in a philosophy student's logical toolkit.

In this chapter, we will introduce a formal language in which to represent arguments of propositional logic, a semantic framework in which to assess their validity, and a deductive system in which to carry out proofs.
We will then proceed to show that this deductive system is both sound and complete.

[^classical]: Truth-functional, or Boolean, propositional logic is often referred to as _classical_ propositional logic.
This label is a misnomer, for truth-functional propositional logic is neither classical in the sense of being the first system of propositional logic to have been studied, nor in the sense of having its origin in Greek or Latin antiquity.
The use of the label 'classical' to describe truth-functional propositional logic seems to have gained widespread usage in the mid-20th century, mainly to distinguish truth-functional propositional logic from the alternative intuitionistic, relevantistic and other non-classical systems of propositional logic that began to be studied more widely at that time.

## The Syntax and Semantics of Propositional Logic {#sec-propositional-logic-the-syntax-and-semantics-of-propositional-logic}

### The Language $\Lp$

We begin by defining a formal language for propositional logic, which we will refer to as $\Lp$.
The alphabet for the language consists, first, of an infinite number of symbols:

$$
  \p_1,\p_2,\ldots,\p_n,\ldots
$$

We refer to these symbols as atoms.
In addition to the atoms, the alphabet also includes four special symbols:

$$
  \neg\hspace{0.05in},\hspace{0.05in} \conj\hspace{0.05in},\hspace{0.05in}
  \disj\hspace{0.05in},\hspace{0.05in} \imp
$$

These are referred to collectively as propositional connectives, and, respectively, as the negation operator ($\neg$), the conjunction operator ($\conj$), the disjunction operator ($\disj$), and the conditional operator ($\imp$).
The latter three connectives (i.e., $\conj, \disj$, and $\imp$) are referred to as binary connectives, whereas the negation operator is referred to as a unary connective.

Lastly, the alphabet for $\Lp$ also includes the left and right parentheses:

$$
(\hspace{0.07in},\hspace{0.07in})
$$

As always, expressions of the language are finite strings of symbols taken from its alphabet.
The sentences of the language are given by the following inductive definition:

:::{#def-sentences-p .definition}

The sentences of $\Lp$ are defined inductively as follows:

1. Any expression consisting of a single atom is a sentence.

2. If $\ph$ is a sentence, then the expression $(\neg \ph)$ is a sentence.

3. If $\ph$ and $\psi$ are sentences and $\ast$ is a binary connective, then the expression $(\ph\ast\psi)$ is a sentence.

:::

Sentences of $\Lp$ include:

i. $\p_7$

ii. $(\neg \p_2)$

iii. $(\p_4 \disj \p_{21})$

iv. $(\neg(\neg \p_{14}))$

v. $((\p_3\imp (\neg \p_3)) \conj (\p_{21}\disj \p_{3}))$

vi. $(\p_{16}\imp(\p_{16}\conj (\p_{16} \imp \p_{16})))$

We refer to those sentences consisting of a single atom as atomic sentences.
The sentence $(\neg \ph)$ is referred to as the negation of $\ph$.
If $\ph$ is either an atomic sentence or the negation of an atomic sentence, we refer to $\ph$ as a literal.
The sentence $(\ph\conj\psi)$ is referred to as the conjunction with left conjunct $\ph$ and right conjunct $\psi$, or simply the conjunction of $\ph$ and $\psi$.
The sentence $(\ph\disj \psi)$ is referred to as the disjunction with left disjunct $\ph$ and right disjunct $\psi$, or simply the disjunction of $\ph$ and $\psi$.
The sentence $(\ph\imp \psi)$ is referred to as the conditional with antecedent $\ph$ and consequent $\psi$.
Conjunctions, disjunctions, and conditionals are referred to, collectively, as binary compounds.

We have not yet shown that the labels negation, conjunction, disjunction, etc., are mutually exclusive.
That is, we have not yet shown that a given sentence cannot, for example, be both a conjunction and a conditional.
Nor have we shown that a sentence which is a conjunction must have unique left and right conjuncts.
We will soon confirm that this is indeed the case, but for now we turn to the task of specifying a semantics for the language.

:::{#exr-omit-parens .exercise}
{{< include /exercises/omit-parens.qmd >}}
:::

:::{#exr-Lp-syntax .exercise}
{{< include /exercises/Lp-syntax.qmd >}}
:::

### Truth Functions and the Propositional Connectives

The non-logical elements of the syntax of $\Lp$ are the atoms.
These, naturally, are meant to stand for the simple propositions out of which compound propositions will be constructed.
But what exactly is a proposition?
How we choose to model propositions in our semantics will depend, in large part, on the patterns of inference that we seek to represent in our logic.
This, in turn, will depend on the intended meanings of the logical elements of the syntax---that is, on the intended meanings of the propositional connectives.

Consider the conjunction operator $\conj$.
Viewed as a proposition forming operation, this operator maps two propositions, signified by the sentences $\ph$ and $\psi$, to a new compound proposition signified by their conjunction $(\ph\conj\psi)$.
By the latter, we mean a proposition that is true just in case both of the propositions signified by its conjuncts are true.
Setting aside the particulars, the conjunction operator, then, maps two propositions to a new proposition whose truth value is a function of the truth values of the two propositions from which it was constructed.
The negation operator, works the same way.
It maps a single proposition, signified by the sentence $\ph$, to a new proposition, signified by $(\neg\ph)$, the truth value of which is a function of the truth value of $\ph$ -- false, if it is true, and true if it is false.
Our intended semantics for the logical connectives may thus be described as a 'truth-functional' semantics.
This means that the truth values of compound sentences will be fully determined by the truth values of the component sentences out of which they are formed.
In this way, the truth values of all the sentences of the language will supervene on the truth values of the atomic ones.

While it is true that the atomic sentences represent simple propositions, the only feature of these propositions that is semantically relevant in the sense that it contributes to assessing the truth values of the sentences in the language is their own truth or falsehood.
Thus, in this context, we may think of a simple proposition as nothing more than the bearer of a truth value, and the possible semantic values of the atoms as the possible truth values of the propositions they express.
The only assumptions we will make about these simple propositions are (1) that each is _logically contingent_ in the sense that each may be either true or false; and (2) that they are _logically independent_ of each other in the sense that the truth or falsehood of any one such proposition imposes no constraints on the truth or falsehood of any other.
In sum, we will include among our interpretations of the language all possible assignments of truth values to the atoms.

:::{#def-p-interpretation .definition}
An _interpretation_ of the language $\Lp$ is a function $\sigma$ which assigns to each of the atoms a truth value, i.e., an object from the set $\{\true, \false\}$.
:::

The semantic rules for the language must specify how a given interpretation $\si$ determines a truth valuation $val^\si$ for the language.
For the atomic sentences, the truth value is given directly by the interpretation, as follows:

(S1): If $\ph$ is an atomic sentence, then $val^\si(\ph)=\si(\ph)$.[^atom]

[^atom]: Strictly speaking, the occurrence of '$\ph$' that appears as an argument of $val^\si$ stands for an atomic sentence, whereas the occcurence of '$\ph$' that appears as an argument of $\si$ stands for an atom.
However, for ease of exposition, we will generally treat as identical an atomic sentence and the atom from which it is composed.

To assign truth values to compound sentences, we must introduce additional semantic rules, specifying the meaning of the propositional connectives.
We will do so with the aim of interpreting the propositional connectives as effecting roughly the same semantic operations as the ordinary English locutions to which they correspond in the following table:

| Connective | Operator    | English Operation                         |
|:----------:|:------------|:------------------------------------------|
| $\neg$     | negation    | It is not the case that $\smallblank$.    |
| $\conj$    | conjunction | $\cdots$ and $\smallblank$.               |
| $\disj$    | ddisjunction| $\cdots$ or $\smallblank$ (or both).      |
| $\imp$     | conditional | If $\cdots$, then $\smallblank$.          |

: The intended meanings of the propositional connectives

What defines each of these operations is the specific way in which the truth or falsity of compound sentences resulting from their application is related to the truth values of the component sentences to which they are applied.
For example, negation is an operation which takes a sentence and returns a sentence with the opposite truth value, conjunction is an operation which takes two sentences and returns a true sentence if and only if both sentences are true, and so forth.
To formalize these semantic operations, we will utilize the notion of a truth function:

:::{#def-truth-function .definition}
An _$n$-ary truth function_ is a function which takes $n$ truth values ($n\geq 1$) and returns a truth value.
:::

:::{#exr-truth-functions .exercise}
{{< include /exercises/truth-functions.qmd >}}
:::  

The following four truth functions describe the intended operation of each of the four propositional connectives:

$$
\begin{align*}
  f_\neg(\al)=\left\{\begin{array}{ll}
                       \false & \textrm{if }\al=\true   \\
                       \true  & \textrm {if }\al=\false
                     \end{array}
  \right.
\end{align*}
$$

$$
\begin{align*}
  f_\conj(\al,\be)=\left\{\begin{array}{ll}
                            \true  & \textrm{if }\al=\true\textrm{ and }\be=\true \\
                            \false & \textrm {otherwise}
                          \end{array}
  \right.
\end{align*}
$$

$$
\begin{align*}
  f_\disj(\al,\be)=\left\{\begin{array}{ll}
                            \false & \textrm{if }\al=\false\textrm{ and }\be=\false \\
                            \true  & \textrm {otherwise}
                          \end{array}
  \right.
\end{align*}
$$

$$
\begin{align*}
  f_\imp(\al,\be)=\left\{\begin{array}{ll}
                           \false & \textrm{if }\al=\true\textrm{ and }\be=\false \\
                           \true  & \textrm {otherwise}
                         \end{array}
  \right.
\end{align*}
$$

To say that these truth functions describe the operations of the  propositional connectives is to assert, for example, that the truth value of the negation of a sentence is determined by applying the function $f_\neg$ to the truth value of that sentence.
Likewise, the truth value of the disjunction of two sentences is the truth value returned by the function $f_\disj$, when its first argument is the truth value of the left disjunct and its second argument the truth value of the right.
This idea is captured by the following two semantic rules:

(S2): For any sentence $\ph$:
$$
  val^\si((\neg\ph))=f_\neg(val^\si(\ph))
$$

(S3): For any sentences $\ph$ and $\psi$ and any binary connective $\ast$:
$$
  val^\si((\ph\ast\psi))=f_\ast(val^\si(\ph), val^\si(\psi))
$$

Rules (S1), (S2), and (S3) impose constraints on the truth valuation $val^\si$.
However, in order for these constraints to comprise a set of semantic rules, it must be the case that, for every interpretation $\si$ there exists one and only one truth valuation $val^\si$ that satisfies these constraints.
As yet, we have not established that this is the case, for we have not yet proven that every compound sentence in $\Lp$ has a _unique_ decomposition into simpler ones.
If, for example, a single sentence were to be both the negation of $\ph$ _and_ the conjunction of $\psi$ and $\chi$, then it may be that the rules (S2) and (S3) cannot be jointly satisfied since each may require $val^\si$ to assign different truth values to this sentence.
In the following section we will prove that the rules (S1), (S2), and (S3) do, in fact, constitute a consistent set of semantic rules for the language by showing that the sentences of $\Lp$  are uniquely decomposable.[^unique-decomposition]

[^unique-decomposition]: For more on unique decomposability, see [Appendix @sec-induction-unique-decomposition].

### Unique Decomposition

In order to show that, for any interpretation $\si$, the rules (S1)-(S3) determine a unique truth valuation of the sentences of $\Lp$, we must show that every non-atomic sentence admits of a unique decomposition.
This claim can be formulated as follows:

:::{#thm-unique-decomposition .theorem}

For every sentence $\ph$, exactly one of the following claims holds:

1. $\ph$ is an atomic sentence.

2. There exists a unique sentence $\psi$ such that $\ph$ is the sentence $(\neg\psi)$.

3. There exist unique sentences $\psi$ and $\chi$ and a unique binary connective $*$, such that $\ph$ is the sentence $(\psi*\chi)$.
:::

To prove this theorem, we begin by observing the following obvious syntactic facts:

:::{#prp-syntax-1 .proposition}
No negation is an atomic proposition.

:::{.proof}
Every negation begins with the symbol $($, but every atomic sentence begins with an atom.
:::
:::

:::{#prp-syntax-2 .proposition}
No binary compound is an atomic sentence.

:::{.proof}
Every binary compound begins with the symbol $($, but every atomic sentence begins with an atom.
:::
:::

:::{#prp-syntax-1 .proposition}
No negation is a binary compound.

:::{.proof}
Every negation begins with the symbols $(\neg$, but every binary compound begins with either the symbols $(\p_n$, where $\p_n$ is an atom, or the symbols $(($.
:::
:::

From these three propositions it follows that, for every sentence $\ph$, exactly one of the following three claims holds:

1. $\ph$ is an atomic sentence.

2. $\ph$ is a negation.

3. $\ph$ is a binary compound.

Moreover, it is easy to show that every negation can be uniquely decomposed:

:::{#prp-negation-ud .proposition}
If $(\neg\ph)=(\neg\psi)$, then $\ph=\psi$.

:::{.proof}
Since $(\neg\ph)=(\neg\psi)$, removing $(\neg$ from the beginning of both of these expressions results in identical expressions.
Thus, $\ph)=\psi)$.
But now removing $)$ from the end of both of these expressions again results in identical expressions.
Hence, $\ph=\psi$.
:::
:::

So, if $\ph$ is a negation, there exists a unique sentence $\psi$, such that $\ph=(\neg\psi)$.
All that remains in order to establish @thm-unique-decomposition is to show that, if $\ph$ is a binary compound, there exist unique sentences $\psi$ and $\chi$ and a unique binary connective $\ast$, such that $\ph=(\psi*\chi)$.
To help prove this claim, we introduce the following terminology:

:::{#def-proper-prefix .definition}
A nonempty expression $\ph$ is a _proper prefix_ of $\psi$ (written $\ph<\psi$) iff there exists a nonempty expression $\chi$ such that $\psi$ is the expression $\ph\chi$ (i.e., the result of concatenating the expressions $\ph$ and $\chi$).
:::

:::{#def-balanced-expr .definition}
Let $w$ be the following function assigning numbers to the symbols in the alphabet of $\Lp$:
$$
  \begin{align*}
    w(s)=\left\{\begin{array}{rl}
                  1  & \textrm{if } s \textrm{ is the symbol } ( \\
                  -1 & \textrm{if } s \textrm{ is the symbol } ) \\
                  0  & \textrm{otherwise}\end{array}\right.
  \end{align*}
$$

Let $\ph$ be the expression $s_1s_2\cdots s_n.$ The _weight_ of $\ph$ is the quantity:

$$
w(\ph)=\sum_{i=1}^n w(s_i)
$$

An expression $\ph$ is _balanced_ if the following two conditions hold:

1. $w(\ph)=0$

2. If $\psi<\ph$, then $w(\psi)\neq 0$.
:::

:::{#thm-balanced .theorem}
Every sentence of $\Lp$ is a balanced expression.

:::{.proof}
The proof proceeds by induction on the sentences.
First, let $\ph$ be an atomic sentence.
Since $w(\p_n)=0$, for $n=1,2,\ldots$, we have $w(\ph)=0$.
Moreover, since $\ph$ has no proper prefixes, it follows that $\ph$ is balanced.

Now, consider the sentence $(\neg\ph)$, and suppose that $\ph$ is balanced.
Then:
$$
    w((\neg\ph))=w(()+w(\neg)+w(\ph)+w())=1+0+0+(-1)=0
$$
Now, suppose for contradiction that there exists a $\psi<(\neg\ph)$ such that $w(\psi)=0$.
Since the expressions $($, $(\neg$, and $(\neg\ph$ all have a weight of $1$, $\psi$ can be none of these expressions.
Thus, $\psi$ must be an expression of the form $(\neg \chi$, where $\chi<\ph$.
Moreover, since $w(\psi)=0$ and $w((\neg)=1$, it follows that $w(\chi)=-1$.
Hence, $\ph$ has a proper prefix with a weight of $-1$.
Since atomic sentences have no proper prefixes, it follows that $\ph$ is not atomic.
But every non-atomic sentence begins with $($ and since $w(()=1$, every non-atomic sentence has a proper prefix of weight 1.
Thus, $\ph$ has both a proper prefix of weight $1$ and a proper prefix of weight $-1$.
But this implies that $\ph$ also has a proper prefix of weight $0$ since the weight of successive proper prefixes can only either increase by 1, decrease by 1, or remain the same.
The existence of such a proper prefix, however, contradicts our assumption that $\ph$ is balanced.
Thus, we have shown that if $\ph$ is balanced, $(\neg \ph)$ is balanced as well.

Lastly, consider the sentence $(\ph\ast\psi)$, where $\ast$ is a binary connective, and suppose that $\ph$ and $\psi$ are balanced expressions.
Then:
$$
    w((\ph\ast\psi))=w(()+ w(\ph) + w(\ast) + w(\psi) + w())=1+ 0 + 0 + 0 + ( - 1) = 0
$$
Now, suppose for contradiction that there exists a $\chi<(\ph\ast\psi)$ such that $w(\chi)=0$.
Since the expressions $($, $(\ph$, $(\ph\ast$, $(\ph\ast\psi$ all have a weight of $1$, $\chi$ can be none of these expressions.
Thus, $\chi$ must either be (i) an expression of the form $(\rho$, where $\rho<\ph$ or (ii) $(\ph\ast\rho$, where $\rho<\psi$.

In case (i), since $w((\rho) = 0$, and $w(()=1$, it follows that $w(\rho)=-1$.
Hence, $\ph$ has a proper prefix with a weight of $-1$.
Since atomic sentences have no proper prefixes, it follows that $\ph$ is not atomic.
But every non-atomic sentence begins with $($ and since $w(()=1$, every non-atomic sentence has a proper prefix of weight 1.
Thus, $\ph$ has both a proper prefix of weight $1$ and a proper prefix of weight $-1$.
But this implies that $\ph$ also has a proper prefix of weight $0$.
The existence of such a proper prefix, however, contradicts our assumption that $\ph$ is balanced.

In case (ii), since $w((\ph\ast\rho) = 0$, and $w((\ph\ast)=1$, it follows that $w(\rho)=-1$.
Hence, $\psi$ has a proper prefix with a weight of $-1$.
Since atomic sentences have no proper prefixes, it follows that $\psi$ is not atomic.
But every non-atomic sentence begins with $($ and since $w(()=1$, every non-atomic sentence has a proper prefix of weight 1.
Thus, $\psi$ has both a proper prefix of weight $1$ and a proper prefix of weight $-1$.
But this implies that $\psi$ also has a proper prefix of weight $0$.
The existence of such a proper prefix, however, contradicts our assumption that $\psi$ is balanced.

Thus, if $\ph$ and $\psi$ are both balanced expressions, so is $(\ph\ast\psi)$.
This completes the proof.
:::
:::

The following theorem is a direct corollary of @thm-balanced.

:::{#thm-no-prefix .theorem}
No sentence of $\Lp$ is a proper prefix of another.

:::{.proof}
Suppose, for contradiction, that $\ph$ and $\psi$ are sentences and that $\ph<\psi$.
By @thm-balanced both $\ph$ and $\psi$ are balanced.
Since $\ph$ is balanced, $w(\ph)=0$.
This, however, contradicts the assumption that $\psi$ is balanced, since $\ph$ is a proper prefix of $\psi$.
:::
:::

With this result in hand, we can now complete our proof of @thm-unique-decomposition by showing that every binary compound can be uniquely decomposed into simpler sentences:

:::{#prp-binary-ud .proposition}
Let $\ph$ and $\psi$ be any sentences and $\ast$ a binary connective.
If $(\ph*\psi)=(\ph'*'\psi')$, where $\ph'$ and $\psi'$ are sentences and $\ast'$ a binary connective, then $\ph=\ph'$, $\ast=\ast'$ and $\psi=\psi'$.

:::{.proof}
Since $(\ph\ast\psi)=(\ph'\ast'\psi')$, removing the outermost pair of parentheses from both of these expressions results in identical expressions.
Thus, $\ph\ast\psi=\ph'\ast'\psi'$.
Now, suppose for contradiction that $\ph\neq \ph'$.
Then, either $\ph<\ph'$ or $\ph'<\ph$.
But either of these claims contradicts @thm-no-prefix.
Hence, $\ph=\ph'$.
But then removing $\ph$ from the beginning of $\ph\ast\psi$ and $\ph'$ from the beginning of $\ph'\ast'\psi'$ results in identical expressions.
Thus, $\ast \psi=\ast' \psi'$ and so $\ast=\ast'$.
But then removing $\ast$ from the beginning of $\ast \psi$ and $\ast'$ from the beginning of $\ast' \psi'$ again results in identical expressions.
Hence, $\psi=\psi'$.
:::
:::

It follows from the fact that, with respect to @def-sentences-p, the set of sentences of $\Lp$ are uniquely decomposable that, for any given interpretation $\si$, there is one and only one truth valuation $val^\si$ satisfying conditions (S1), (S2), and (S3).
Thus, we are justified in treating these conditions as constituting a set of semantic rules for the language.

:::{#exr-no-parens .exercise}
{{< include /exercises/no-parens.qmd >}}
:::

:::{#exr-polish .exericse}
{{< include /exercises/polish.qmd >}}
:::

For the purpose of proving unique decomposition, it was necessary to be scrupulous in our use of parentheses.
From this point forward, however, for the sake of readability, we may be somewhat more lax.
In particular, when writing sentences, we will omit the outermost pair of parentheses.
We will also assume an order of operations for the propositional connectives that will allow us to express sentences using fewer parentheses than are strictly required by the grammatical rules of $\Lp$.
In accordance with this order of operations, negations is to be parenthesized first, in as narrow a manner as possible, then conjunctions and disjunctions, and finally conditionals.
Thus, for example, to express the sentence:
$$
  ((\p_1\conj\p_2)\imp (\neg(\neg\p_3)))
$$
we may write:
$$
\p_1\conj\p_2\imp \neg\neg\p_3
$$

### Truth Tables

Now that we have specified the semantic rules for the language, all of the standard semantic notions introduced in Chapter 1 (e.g., validity, logical truth, logical equivalence, etc.) are defined just as before.
It will be useful, however, to recast these semantic notions in terms of truth functions.
To this end, the following definition will be helpful:

:::{#def-truth-function-for-sentence .definition}
Let $\ph$ be any sentence containing only atoms that appear among $\p_{1},\ldots,\p_{n}$.
The _$n$-ary truth function for $\ph$_ is the $n$-ary truth function $f_\ph^n$ defined by:
$$
    f_\ph^n(\al_1,\ldots,\al_n)= val^\si(\ph),
$$
where $\si$ is any interpretation such that:
$$
    \si(\p_{i})=\al_i,
$$
for $i=1,\ldots,n$.
:::

Suppose, for example, that $\ph$ is the sentence $(\p_1\imp \p_2)\conj\neg\p_1$.
To evaluate $f_{\ph}^2(\true, \false)$ we must evaluate the truth value of the sentence $\ph$ on an interpretation $\si$ of the language  which assigns to $\p_1$ the value $\true$ and to $\p_2$ the value $\false$.
This is:

$$
\begin{align*}
val^\si((\p_1\imp \p_2)\conj\neg\p_1) &= f_\conj(val^\si(\p_1\imp\p_2), val^\si(\p_1))\\
&= f_\conj(f_\imp(val^\si(\p_1),val^\si(\p_2)), val^\si(\p_1))\\
&= f_\conj(f_\imp(\true, \false), \true)\\
&= f_\conj(\false, \true)\\  
&= \false
\end{align*}
$$

A particularly convenient way to represent the $n$-ary truth function for $\ph$ is in terms of a _truth table_.
Excluding column headers, the first $n$ columns of each of the $2^n$ rows of the table specify a distinct possible assignment of truth values to the atoms $\p_1,\ldots,\p_n$.
The $(n+1)$-th column then gives the value of the function $f_\ph^n$ for this particular sequence of truth values:

|  $\p_1$  |  $\p_2$  | $\cdots$ |  $\p_n$  |                 $\ph$                  |
| :------: | :------: | :------: | :------: | :------------------------------------: |
| $\true$  | $\true$  | $\cdots$ | $\true$  |  $f_\ph^n(\true,\true,\ldots,\true)$   |
| $\true$  | $\true$  | $\cdots$ | $\false$ |  $f_\ph^n(\true,\true,\ldots,\false)$  |
| $\vdots$ | $\vdots$ | $\vdots$ | $\vdots$ |                $\vdots$                |
| $\false$ | $\false$ | $\false$ | $\false$ | $f_\ph^n(\false,\false,\ldots,\false)$ |

When populating the first $n$ columns in such a truth table, it is important to ensure that all possible assignments of truth values to the atoms $\p_1,\ldots,\p_n$ are countenanced.
The most straightforward way to ensure that this is the case is to adopt the following procedure: for $m=1,\ldots,n$, fill in the $m$th column with alternating between blocks of $\true$'s and $\false$'s, where the size of the blocks is equal to $2^{n-m}$ rows.
So, for example, if $n=3$, fill in the first column with alternating blocks of $\true$'s and $\false$'s of size $2^{3-1}=2^2=4$ rows.
Then, fill in the second column with alternating blocks of $\true$'s and $\false$'s of size $2^{3-2}=2^1=2$ rows.
Finally, fill in the third column with alternating blocks of $\true$'s and $\false$'s of size $2^{3-3}=2^0=1$ row.[^counting]

[^counting]: Add footnote on counting.

When writing the truth table for a sentence, it is often convenient to omit columns corresponding to atoms not appearing in that sentence since the truth values of these atoms have no effect on the sentence's truth value.
In addition, one often includes supplementary columns listing the truth values of certain component sentences (indicated in the column header) which may aid in the computation of the sentence's truth value.
Thus, for example, a truth table for the sentence $\neg(\p_3\conj \p_1)\rightarrow \p_1 \disj \p_2$ may be written:

|  $\p_1$  |  $\p_2$  |  $\p_3$  | $\p_3\conj\p_1$ | $\neg(\p_3\conj\p_1)$ | $\p_1\vee\p_2$ | $\neg(\p_3\conj \p_1)\rightarrow \p_1 \disj\p_2$ |
| :------: | :------: | :------: | :-------------: | :-------------------: | :------------: | :----------------------------------------------: |
| $\true$  | $\true$  | $\true$  |     $\true$     |       $\false$        |    $\true$     |                     $\true$                      |
| $\true$  | $\true$  | $\false$ |    $\false$     |        $\true$        |    $\true$     |                     $\true$                      |
| $\true$  | $\false$ | $\true$  |     $\true$     |       $\false$        |    $\true$     |                     $\true$                      |
| $\true$  | $\false$ | $\false$ |    $\false$     |        $\true$        |    $\true$     |                     $\true$                      |
| $\false$ | $\true$  | $\true$  |    $\false$     |        $\true$        |    $\true$     |                     $\true$                      |
| $\false$ | $\true$  | $\false$ |    $\false$     |        $\true$        |    $\true$     |                     $\true$                      |
| $\false$ | $\false$ | $\true$  |    $\false$     |        $\true$        |    $\false$    |                     $\false$                     |
| $\false$ | $\false$ | $\false$ |    $\false$     |        $\true$        |    $\false$    |                     $\false$                     |                    

Now, let $\Ga$ be a set of sentences and let $\ph$ be a sentence.
Suppose that the only atoms appearing in the sentences in $\Ga\cup\{\ph\}$ are among $\p_1,\ldots,\p_n$.
Then, $\Ga\models\ph$ iff, for any truth values $\al_1,\ldots,\al_n$: if $f^n_\psi(\al_1,\ldots,\al_n)=\true$, for all $\psi\in\Ga$, then $f^n_\ph(\al_1,\ldots,\al_n)=\true$.
In simple cases, this can be confirmed directly by means of a truth table.
For example, the following truth table can be used to confirm that $\neg\p_1,\p_1\vee\p_2\models\neg\neg\p_2$:

|  $\p_1$  |  $\p_2$  | $\neg\p_1$ | $\p_1\vee\p_2$ | $\neg\neg\p_2$ |
| :------: | :------: | :--------: | :------------: | :------------: |
| $\true$  | $\true$  |  $\false$  |    $\true$     |    $\true$     |
| $\true$  | $\false$ |  $\false$  |    $\true$     |    $\false$    |
| $\false$ | $\true$  |  $\true$   |    $\true$     |    $\true$     |
| $\false$ | $\false$ |  $\true$   |    $\false$    |    $\false$    |

The only row which corresponds to an assignment of truth values to the atoms which makes both of the premises true is row 3.
But, in that row, the conclusion is true as well.
Hence, the argument is valid.

We may also use truth tables to indicate how the truth of a given compound sentence depends on its (not necessarily atomic) components.
For example, if $\ph$ and $\psi$ are any two sentences, we may write a truth table for the sentence $\neg\ph\rightarrow\psi$ as follows:

|  $\ph$   |  $\psi$  | $\neg\ph$ | $\neg\ph\imp\psi$ |
| :------: | :------: | :-------: | :---------------: |
| $\true$  | $\true$  | $\false$  |      $\true$      |
| $\true$  | $\false$ |  $\true$  |      $\true$      |
| $\false$ | $\true$  |  $\true$  |      $\true$      |
| $\false$ | $\false$ |  $\true$  |     $\false$      |

In a schematic truth table like this, all possible truth value assignments to the component sentences $\ph$ and $\psi$ are countenanced.
In fact, depending on the sentences $\ph$ and $\psi$, certain of these assignments may not be possible.
For example, if $\ph$ is the sentence $\p_3$ and $\psi$ the sentence $\neg\p_3$, then there is no truth value assignment which assigns to both $\ph$ and $\psi$ the value $\true$.
Nevertheless, if we wish to establish semantic claims about _all_ possible instantiations of a sentence schema, we must consider all possible valuations of $\ph$ and $\psi$ since, among the instantiations of this schema, are those in which $\ph$ and $\psi$ are distinct atomic sentences.

:::{#exr-truth-tables .exercise}
{{< include /exercises/truth-tables.qmd >}}
:::

In contexts in which we are only concerned with the truth values of sentences and not their syntax, we may allow for the use of certain syntactically ambiguous expressions provided all possible disambiguations of these expressions are logically equivalent to one another.
For example, we will often omit the parentheses from nested conjunctions and disjunctions since the truth functions for such sentences are order invariant.
Thus, for example, to express the conjunction of the sentences $\ph_1,\ldots,\ph_n$ we may simply write:
$$
  \ph_1 \conj \cdots \conj \ph_n
$$
However one opts to parenthesize this expression to render it a sentence, the result will be a sentence that is true iff all of the sentences $\ph_1,\ldots,\ph_n$ are true.
Likewise, any disambiguation of the disjunction:
$$
\ph_1\disj\cdots\disj\ph_n
$$
is a sentence that is false iff all of the sentences $\ph_1,\ldots,\ph_n$ are false.

:::{#exr-expressing-semantic-notions .exercise}
{{< include /exercises/expressing-semantic-notions.qmd >}}
:::

### Truth-Functional Completeness

As we have seen, sentences can be thought of as expressing truth functions.
In particular, a sentence $\ph$ containing only atoms among $\p_1,\ldots,\p_n$, can be thought of as expressing the truth function $f_\ph^n$ that maps the truth values of these atomic sentences on a given interpretation to the truth value of the sentence itself on that same interpretation.
So, for example, a sentence like $\neg\p_1\vee \p_2$ expresses the truth function:

$$
\begin{align*}
  f^2_{\neg\p_1\vee\p_2}(\al,\be) & = f_\vee(f_{\neg\p_1}^2(\al,\be), f^2_{\p_2}(\al,\be))                     \\
                                  & = f_\vee(f_\neg(f_{\p_1}^2(\al,\be)), \be)                               \\
                                  & = f_\vee(f_\neg(\al),\be)                                                \\
                                  & = \left\{\begin{array}{ll}
                                               \false & \textrm{if }f_\neg(\al)=\false\textrm{ and }\be=\false \\
                                               \true  & \textrm{otherwise}
                                             \end{array}\right. \\
                                  & = \left\{\begin{array}{ll}
                                               \false & \textrm{if }\al=\true\textrm{ and }\be=\false \\
                                               \true  & \textrm{otherwise}
                                             \end{array}\right.
\end{align*}
$$

This truth function is described by the following truth table:

|  $\p_1$  |  $\p_2$  | $\neg\p_1\disj\p_2$ |
| :------: | :------: | :-----------------: |
| $\true$  | $\true$  |       $\true$       |
| $\true$  | $\false$ |      $\false$       |
| $\false$ | $\true$  |       $\true$       |
| $\false$ | $\false$ |       $\true$       |

Note that this same truth function can also be expressed by the sentence $\p_1\imp\p_2$:

|  $\p_1$  |  $\p_2$  | $\p_1\imp\p_2$ |
| :------: | :------: | :------------: |
| $\true$  | $\true$  |    $\true$     |
| $\true$  | $\false$ |    $\false$    |
| $\false$ | $\true$  |    $\true$     |
| $\false$ | $\false$ |    $\true$     |

The particular truth function described by the four rows of this truth table is thus expressible both by a sentence which involves the connectives $\neg$ and $\disj$, and also by a sentence which involves the single connective $\imp$.
The question, then, naturally arises as to which truth functions can be expressed by which connectives, and, in particular, whether there are any sets of connectives by means of which _every_ truth function can be expressed.

:::{#def-truth-completeness .definition}
Let $C$ be a set of propositional connectives, i.e., $C\subset\{\neg,\conj,\disj,\imp\}$.
We say that the sentence $\ph$ is _expressible in $C$_ if the only connectives appearing in $\ph$ are members of $C$.
We say that the $n$-ary truth function $f$ is _expressible in $C$_ if $f=f_\ph^n$, for some sentence $\ph$ expressible in $C$.
We say that $C$ is a _truth
    functionally complete_ set of connectives if every truth function is expressible in $C$.
:::

:::{#exr-dual .exercise}
{{< include /exercises/dual.qmd >}}
:::

Are there any sets of propositional connectives which are truth functionally complete, and, if so, what are they?
We will begin by giving an informal argument to illustrate why the set of connectives $\{\neg,\conj,\disj\}$ is truth functionally complete.

Consider the following truth table for an arbitrarily chosen 3-ary truth function $f$.

|  $\p_1$  |  $\p_2$  |  $\p_3$  |   $f$    |
| :------: | :------: | :------: | :------: |
| $\true$  | $\true$  | $\true$  | $\true$  |
| $\true$  | $\true$  | $\false$ | $\false$ |
| $\true$  | $\false$ | $\true$  | $\true$  |
| $\true$  | $\false$ | $\false$ | $\false$ |
| $\false$ | $\true$  | $\true$  | $\true$  |
| $\false$ | $\true$  | $\false$ | $\true$  |
| $\false$ | $\false$ | $\true$  | $\false$ |
| $\false$ | $\false$ | $\false$ | $\false$ |

How might we construct a sentence $\ph$ expressible in $\{\neg,\conj,\disj\}$ such that $f^3_\ph=f$?
Note that the function $f$ returns the truth value $\true$ iff its arguments are those given in either the first, third, fifth, or sixth rows of the above truth table.
Thus, we might start by formulating our desired sentence as a disjunction of these four possibilities:
$$
  Row_1 \vee Row_3 \vee Row_5 \vee Row_6
$$
$Row_1$, in this case, is a sentence which is true iff $\p_1,\p_2,$ and $\p_3$ are all true.
This sentence can be formulated by means of the following conjunction:
$$
  \p_1\conj\p_2\conj\p_3
$$
$Row_3$ is a sentence which is true iff $\p_1$ is true, $\p_2$ is false, and $\p_3$ is true.
This can be formulated as follows:
$$
  \p_1\conj\neg\p_2\conj\p_3
$$
Formulating the sentences $Row_5$ and $Row_6$ in similar fashion, we can express the sentence $\ph$ by the following disjunction:
$$
  (\p_1\conj\p_2\conj\p_3) \vee (\p_1\conj\neg\p_2\conj\p_3) \vee (\neg\p_1\conj\p_2\conj\p_3) \vee (\neg\p_1\conj\p_2\conj\neg\p_3)
$$

With only one exception, this technique is fully generalizable, and can be used to construct a sentence in $\{\neg,\conj,\disj\}$ which expresses any truth function with any number of arguments.
The one case that it doesn't cover is the degenerate case in which the truth function in question always returns the truth value $\false$.
But this truth function is expressible by the sentence $\p_1\conj\neg\p_1$.
So the set of connectives $\{\neg,\conj,\disj\}$ is truth-functionally complete.

In fact, the above argument establishes a stronger claim, namely, that every sentence of $\Lp$ is equivalent to a disjunction of conjunctions of literals, i.e, a sentence of the form:
$$
  (\ph_{1,1}\conj\cdots\conj \ph_{1,k})\disj \cdots \disj (\ph_{n,1}\conj\cdots\conj \ph_{n,k}),
$$
where $\ph_{i,j}$ is either an atomic sentence or its negation.
Such an equivalent form is referred to as the _disjunctive normal form_ of the sentence.

:::{#exr-conj-normal-form .exercise}
{{< include /exercises/conj-normal-form.qmd >}}
:::

If $C$ is a truth functionally complete set of connectives, it suffices to show that the set of connectives $C^*$ is truth functionally complete, to show that every sentence expressible in $C$ is logically equivalent to some sentence expressible in $C^*$.
Thus, for example, in light of the fact that $\{\neg,\conj,\disj\}$ is truth-functionally complete, we can prove that $\{\neg,\disj\}$ is also truth-functionally complete by observing that:
$$
  \ph\conj\psi\equiv \neg(\neg\ph\disj\neg\psi).
$$
Furthermore, from the fact that $\{\neg,\disj\}$ is truth functionally complete, we can show that $\{\neg,\imp\}$ is truth functionally complete by noting that:
$$
  \ph\disj\psi\equiv \neg\ph\imp\psi.
$$
Thus, a number of the propositional connectives in $\Lp$ are, from a semantic point of view, superfluous.
Even if we were only to include in our language the two propositional connectives $\neg$ and $\imp$, we do not lose any expressive power---every truth function remains expressible.

:::{#exr-sheffer .exercise}
{{< include /exercises/sheffer.qmd >}}
:::

## Proofs in Propositional Logic {#sec-propositional-logic-proofs-in-propositional-logic}

### Natural Deduction in Propositional Logic

In this section, we introduce a proof system for reasoning in propositional logic.
The initial version of this system will be set up with the aim of ensuring that proofs follow intuitively recognizable patterns of reasoning, and thus are relatively easy to devise.
The naturalness of proofs in the system is owing, in large part, to the following two facts: (1) the proof system emphasizes rules of inference over axioms; and (2) in addition to direct proofs, the system will also license various hypothetical methods of proof, including the method of proof by contradiction, introduced in Chapter 2.
While these two features of the system will greatly simplify the construction of proofs, as we shall see, neither of these features is essential to formulating a sound and complete proof system for propositional logic.
Accordingly, once we have introduced the full system, we will explore how it can be simplified and streamlined while preserving its full deductive power.

We refer to the proof system for propositional logic as $\p$.
As with the proof systems that we have already considered, $\p$ will include both direct rules of inference, which license the inference of sentences from sentences, and hypothetical rules of inferences, which license the inference of arguments from arguments.
The direct rules of inference of the system are as follows:[^modus-ponens]

($\neg-$):
$$
\frac{\neg\neg\ph}{\ph}
$$

($\conj+$):
$$
\frac{\ph\,,\,\psi}{\ph\conj\psi}
$$

(L$\conj-$):
$$
\frac{\ph\conj\psi}{\ph}
$$

(R$\conj-$):
$$
\frac{\ph\conj\psi}{\psi}
$$

(L$\disj+$):
$$
\frac{\ph}{\ph\disj\psi}
$$

(R$\disj+$):
$$
\frac{\ph}{\psi\disj\ph}
$$

($\imp-$):
$$
\frac{\ph\,,\,\ph\imp\psi}{\psi}
$$

By means of these direct rules of inference, we can establish such claims as:
$$
  \ph\conj\psi, \ph\imp\chi \provesp \chi\vee\psi
$$
where $\ph,\psi$, and $\chi$ are any sentences of $\Lp$.
The proof is as follows:

:::{.lproof}
    1.  \varphi\wedge\psi           [Premise]
    2.  \varphi                     [L$\wedge-$: 1]
    3.  \varphi\rightarrow\chi      [Premise]
    4.  \chi                        [$\rightarrow-$: 4, 3]
    5.  \chi\vee\psi                [L$\vee+$: 4]
:::

The system $\p$ has no axioms.
Given this fact, it would seem to follow that $\p$ also has no theorems.
For, without axioms, there are no starting points from which theorems can be derived.
But if $\p$ has no theorems, then it certainly is not complete, for completeness requires that every logical truth is a theorem, and there are many sentences of $\Lp$ which are logical truths, e.g., $\p_1\imp\p_1$.
Thus, on pain of incompleteness, we need to ensure that the system is capable of proving all such logical truths.
This will be achieved by adding to the system the following three hypothetical rules of inference:

($\neg+$):
$$
\frac{\Ga,\ph\proves\psi\qquad \Ga,\ph\proves\neg\psi}{\Ga\proves\neg\ph}
$$

($\imp+$):
$$
\frac{\Ga,\ph\proves\psi}{\Ga\proves\ph\imp\psi}
$$

($\vee-$):
$$
\frac{\Ga\proves\ph\vee\psi \qquad  \Ga,\ph\proves\chi \qquad \Ga,\psi\proves\chi}{\Ga\proves\chi}
$$

The first of these rules, ($\neg+$), licenses the method of proof by contradiction.
The following proof illustrates how this rule can be used to show that $\neg\psi, \ph\imp\psi\provesp\neg\ph$:

:::{.lproof}
    1.  \neg\psi, \varphi\rightarrow\psi, \varphi \vdash \varphi                    [Hypothesis]
    2.  \neg\psi, \varphi\rightarrow\psi, \varphi \vdash \varphi\rightarrow \psi    [Hypothesis]
    3.  \neg\psi, \varphi\rightarrow\psi, \varphi \vdash \psi                [$\rightarrow-$: 1]
    4.  \neg\psi, \varphi\rightarrow\psi, \varphi \vdash \neg\psi                   [Hypothesis]
    5.  \neg\psi, \varphi\rightarrow\psi \vdash \neg\varphi                      [$\neg+$: 3, 4]
:::

In Fitch notation, this proof can be expressed as follows:

:::{.lproof}
    1.  | |_  \varphi        
    2.  | |   \varphi\rightarrow\psi      [Premise]
    3.  | |   \psi                        [$\rightarrow-$: 1, 2]
    4.  | |   \neg\psi                    [Premise]
    5.  \neg\varphi                       [$\neg+$: 3, 4] 
:::

Another straighforward consequence of the rule $(\neg+)$ is the law of explosion, which asserts that from a sentence and its negation, anything follows:

:::{#thm-p-explosion .theorem}
$\ph,\neg\ph\provesp\psi$
:::

:::{.lproof}
    1.  | |_  \neg\psi        
    2.  | |   \varphi               [Premise]
    3.  | |   \neg\varphi           [Premise]
    4.  \neg\neg\psi                [$\neg+$: 2, 3] 
    5. \psi                         [$\neg-$: 4]
:::

The hypothetical rule of inference ($\rightarrow -$) is meant to capture the method of suppositional reasoning.
In order to prove a conditional of the form $\ph\imp\psi$, we posit the antecedent $\ph$ as a hypothesis and deduce the consequent $\psi$.
The following theorem illustrates how this method can be used to show that certain sentences are theorems of $\P$.

:::{#thm-conditional-theorems .theorem}
i. $\provesp \ph\imp\ph$

ii. $\provesp \ph\imp(\ph\imp\ph)$

iii. $\provesp (\neg\ph\imp\ph)\imp\ph$
:::

_Proof_.

i.

:::{.lproof}
    1.  \varphi\vdash\varphi               [Hypothesis]
    2.  \vdash\varphi\rightarrow\varphi    [$\rightarrow+$: 1]
:::

In Fitch notation, the proof is simply:

:::{.lproof}
    1.  |   |_  \varphi             
    2.  \varphi\rightarrow\varphi           [$\rightarrow+$: 1]
:::

ii.

:::{.lproof}
    1. \varphi\vdash\varphi                                   [Hypothesis]
    2. \varphi\vdash\varphi\rightarrow\varphi                 [$\rightarrow+$: 1]
    3. \vdash\varphi\rightarrow(\varphi\rightarrow\varphi)    [$\rightarrow+$: 2] 
:::

Note that in the application of the rule ($\imp+$) to line 1, we appeal to the fact that $\{\ph\}=\{\ph\}\cup\{\ph\}$, whereas in the application of this rule to line 2, we appeal to the fact that $\{\ph\}=\emptyset\cup\{\ph\}$.
In Fitch notation this difference shows up in the depth of the subproof:

:::{.lproof}
    1.      |   |_  \varphi
    2.      |   |   |_  \varphi
    3.      |   |   \varphi\rightarrow\varphi               [$\rightarrow+$: 2]
    4.      \varphi\rightarrow(\varphi\rightarrow\varphi)   [$\rightarrow+$: 3]
:::

iii.

:::{.lproof}
    1.      |   |_ \neg\varphi\rightarrow\varphi    
    2.      |   |   |_  \neg\varphi
    3.      |   |   |   \neg\varphi\rightarrow\varphi           [Reiteration: 1]
    4.      |   |   |   \varphi                                 [$\rightarrow-$: 2, 3]
    5.      |   |   \neg\neg\varphi                             [$\neg+$: 2, 4]
    6.      |   |   \varphi                                     [$\neg-$: 5]
    7.      (\neg\varphi\rightarrow\varphi)\rightarrow\varphi   [$\rightarrow+$: 6]
:::

The hypothetical rule of inference ($\disj$-) is intended to capture the method of reasoning by cases.
Given a disjunction $\ph\disj\psi$, it suffices to prove the sentence $\chi$ to show that $\chi$ follows, first, in the case where $\ph$ is supposed true and, second, in the case where $\psi$ is supposed true.
The following theorem illustrates how this method can be used to establish one direction of De Morgan's law equating a disjunction with the negation of the conjunction of the negations of its disjuncts:

:::{#thm-demorgan .theorem}
$\ph\vee\psi\provesp\neg(\neg\ph\conj\neg\psi)$
:::

:::{.lproof}
    1.  \varphi\vee\psi                         [Premise]
    2.  |   |_  \varphi
    3.  |   |   |_  \neg\varphi\wedge\neg\psi
    4.  |   |   |   \neg\varphi                 [L$\wedge-$: 3]
    5.  |   |   |   \varphi                     [Reiteration: 2]
    6.  |   |   \neg(\neg\varphi\wedge\neg\psi) [$\neg+$: 4, 5]
    7.  |   |_  \psi
    8.  |   |   |_  \neg\varphi\wedge\neg\psi
    9.  |   |   |   \neg\psi                    [R$\wedge$-: 8]
    10. |   |   |   \psi                        [Reiteration: 7]
    11. |   |   \neg(\neg\varphi\wedge\neg\psi) [$\neg+$: 9, 10]
    12. \neg(\neg\varphi\wedge\neg\psi)         [$\vee-$: 1, 6, 11]
:::

Note that in Fitch notation, the application of the rule ($\disj\textrm{-}$) appeals to two distinct subproofs, one initiated by the left disjunct of the proven disjunction, and the other by the right.

In addition to the rules of inference included in the proof system $\p$, to shorten and streamline proofs, it is also sometime useful to introduce new 'derived' rules of inference.
To introduce a new derived rule, we must establish that the sentence that results from applying the rule does, in fact, follow from the sentences to which the rule is applied.
So, for instance, given @thm-p-explosion, we can treat explosion as a derived rule of inference, and employ it as in the following proof:

:::{#thm-demorgan-2 .theorem}
$\ph\conj\psi\provesp\neg(\neg\ph\disj\neg\psi)$
:::

:::{.lproof}
    1.  |   |_  \neg\varphi\vee\neg\psi
    2.  |   |   |_  \neg\varphi         
    3.  |   |   |   \varphi\wedge\psi           [Premise]
    4.  |   |   |   \varphi                     [L$\wedge-$: 3]
    5.  |   |   |   \varphi\wedge\neg\varphi    [$\wedge+$: 2, 4]
    6.  |   |   |_  \neg\psi
    7.  |   |   |   \varphi\wedge\psi           [Premise]
    8.  |   |   |   \psi                        [R$\wedge-$: 7]
    9.  |   |   |   \varphi\wedge\neg\varphi    [Explosion: 6, 8]
    10. |   |   \varphi\wedge\neg\varphi        [$\vee+$: 1, 5, 9]
    11. |   |   \varphi                         [L$\wedge-$: 10]
    12. |   |   \neg\varphi                     [R$\wedge-$: 11]
    13. \neg(\neg\varphi\vee\neg\psi)           [$\neg$+: 11, 12]
:::

:::{#exr-proofs-in-p .exercise}
{{< include /exercises/proofs-in-p.qmd >}}
:::

### The Negation-Conditional Fragment of $\p$

As we noted earlier, from a semantic point of view, we can omit from the language $\Lp$ all the propositional connectives apart from the negation operator ($\neg$) and the conditional operator ($\imp$), without any loss of expressive power.
We now observe, in similar fashion, that all the rules of inference of $\p$ excepting those that involve these two connectives can likewise be omitted from the system without any loss of deductive power.

Let $\Lp^-$ be the language whose alphabet consists of all the atoms, the left and right parenthesis symbols, and the propositional connectives $\neg$ and $\imp$.
The sentences of $\Lp^-$ are defined inductively as follows:

1. If $\ph$ is an atomic sentence, then $\ph$ is a sentenceof $\Lp^-$.

2. If $\ph$ is a sentence of $\Lp^-$, then $(\neg\ph)$ is a sentence of $\Lp^-$.

3. If $\ph$ and $\psi$ are sentences of $\Lp^-$, then $(\ph\imp\psi)$ is a sentence of $\Lp^-$.

Let $\p^-$ be the proof system for the language $\Lp^-$ which has no axioms, and which includes the two direct rules of inference:

($\neg-$):
$$
\frac{\neg\neg\ph}{\ph}
$$

($\imp-$):
$$
\frac{\ph\,,\,\ph\imp\psi}{\psi}
$$

and the two hypothetical rules of inference:

($\neg+$):
$$
\frac{\Ga,\ph\proves\psi\qquad \Ga,\ph\proves\neg\psi}{\Ga\proves\neg\ph}
$$

($\imp+$):
$$
\frac{\Ga,\ph\proves\psi}{\Ga\proves\ph\imp\psi}
$$

Conjunctions and disjunctions are not a part of the syntax of the language $\Lp^-$.
Nevertheless, we may introduce the connectives $\conj$ and $\disj$ into the language as metalinguistic shorthand.
In particular, for any sentences $\ph$ and $\psi$ of $\Lp^-$, we will stipulate that:
$$
  \ph\conj\psi\textrm{ stands for the sentence }\neg(\ph\imp\neg\psi)
$$
$$
  \ph\disj\psi\textrm{ stands for the sentence }\neg\ph\imp\psi
$$
Adopting this shorthand, it can be shown that all of the rules of inference, both direct and hypothetical, of the proof system $\p$ are derivable in its negation-conditional fragment.
For example, consider the rule:

($\conj+$):
$$
\frac{\ph\,,\,\psi}{\ph\conj\psi}
$$

In accordance with the shorthand introduced above, this rule asserts: ($\conj+$):
$$
\frac{\ph\,,\,\psi}{\neg(\ph\imp\neg\psi)}
$$
The validity of this rule in the system $\p^-$ can be established as follows:

:::{.lproof}
    1.  |   |_  \varphi\rightarrow\neg\psi
    2.  |   |   \varphi                         [Premise]
    3.  |   |   \neg\psi                        [$\rightarrow-$: 1, 2]
    4.  |   |   \psi                            [Premise]
    5.  \neg(\varphi\rightarrow\neg\psi)        [$\neg+$: 3, 4]       
:::

Likewise, the rule (L$\vee+$) asserts:

(L$\vee+$):
$$
\frac{\ph}{\neg\ph\imp\psi}
$$

The validity of this rule in $\p^-$ can be established as follows:

:::{.lproof}
    1. |    |_  \neg\varphi          
    2. |    |   |_  \neg\psi
    3. |    |   |   \neg\varphi         [Reiteration: 1]
    4. |    |   |   \varphi             [Premise]
    5. |    |   \neg\neg\psi            [$\neg+$: 3, 4]
    6. |    |   \psi                    [$\neg-$: 5]
    7. \neg\varphi\rightarrow\psi       [$\rightarrow+$: 6]   
:::

:::{#exr-negation-conditional-fragment .exercise}
{{< include /exercises/negation-conditional-fragment.qmd >}}
:::

Next, consider the hypothetical rule of inference ($\vee-$).
In accordance with the metalinguistic shorthand introduced above, this rule asserts:

($\vee-$):
$$
\frac{\Ga\proves\neg\ph\imp\psi \qquad \Ga,\ph\proves\psi \qquad \Ga,\psi\proves\chi}{\Ga\proves\chi}
$$

To help derive this rule, we first establish that the following direct rules of inference are valid in $\p^-$:

(Transitivity):
$$
\frac{\ph\imp\psi\,,\,\psi\imp\chi}{\ph\imp\chi}
$$

:::{.lproof}
    1. |    |_  \varphi    
    2. |    |   \varphi\rightarrow\psi      [Premise]
    3. |    |   \psi                        [$\rightarrow-$: 1, 2]
    4. |    |   \psi\rightarrow\chi         [Premise]
    5. |    |   \chi                        [$\rightarrow-$: 3, 4]
    6. \varphi\rightarrow\chi               [$\rightarrow+$: 5]
:::

(Contraposition):
$$
\frac{\neg\ph\imp\psi}{\neg\psi\imp\ph}
$$

:::{.lproof}
    1.  |   |_  \neg\psi
    2.  |   |   |_  \neg\varphi
    3.  |   |   |   \neg\varphi\rightarrow\psi      [Premise]
    4.  |   |   |   \psi                            [$\rightarrow-$: 2, 3]
    5.  |   |   |   \neg\psi                        [Reiteration: 1]
    6.  |   |   \neg\neg\varphi                     [$\neg+$: 4, 5]
    7.  |   |   \varphi                             [$\neg-$: 6]
    8.  \neg\psi\rightarrow\varphi                  [$\rightarrow+$: 7]
:::

Utilizing these derived rules of inference, the validity of the hypothetical rule ($\vee-$) can be established as follows:

:::{.lproof}
    1. \Gamma\vdash\neg\varphi\rightarrow\psi           [Assumption]
    2. \Gamma,\psi\vdash\chi                            [Assumption]
    3. \Gamma\vdash\psi\rightarrow\chi                  [$\rightarrow+$: 2]
    4. \Gamma\vdash\neg\varphi\rightarrow\chi           [Transitivity: 1, 3]
    5. \Gamma\vdash\neg\chi\rightarrow\varphi           [Contraposition: 4]
    6. \Gamma,\varphi\vdash\chi                         [Assumption]
    7. \Gamma\vdash\varphi\rightarrow\chi               [$\rightarrow+$: 6]
    8. \Gamma\vdash\neg\chi\rightarrow\chi              [Transitivity: 5, 7]
    9. \Gamma,\neg\chi\vdash\neg\chi                    [Hypothesis]
    10. \Gamma, \neg\chi\vdash\chi                      [$\rightarrow-$: 8, 9]
    11. \Gamma\vdash\neg\neg\chi                        [$\neg+$: 9, 10]
    12. \Gamma\vdash\chi                                [$\neg-$: 11]
:::

Since all the direct and hypothetical rules of the proof system $\p$ can be derived in the system $\p^{-}$, every proof in the former system can be carried out in the latter.
Thus, we can limit our attention to the negation-conditional fragment of $\p$ without any loss of deductive power.

### A Hilbert-Style Proof System for Propositional Logic

The system $\p^{-}$ represents a significant streamlining of the proof system $\p$.
Nevertheless, it still licenses proofs that utilize hypothetical methods of reasoning, as captured by the rules ($\imp$+) and ($\neg$+).
Can we formulate an even simpler deductive system, which avoids any appeal to such hypothetical rules of inference, but which remains equivalent in deductive power to $\p^{-}$?
As we shall see in this section, the answer to this question is yes.

Let $\Hp$ be a proof system for the language $\Lp^{-}$ of the simple sort defined in Chapter 1, admitting only axioms and direct rules of inference.
The axioms of $\Hp$ will be infinite in number, but will each conform to one of a few schematic forms.
To demarcate the set of axioms, we will specify these schemas and stipulate that every sentence which is an instance of one of these schemas is an axiom of the system.
The three axiom schemas for $\Hp$ are:

(P$1$): $\ph\imp(\psi\imp\ph)$

(P$2$): $(\ph\imp(\psi\imp\chi))\imp((\ph\imp\psi)\imp(\ph\imp\chi))$

(P$3$): $(\neg\ph\imp\neg\psi)\imp(\psi\imp\ph)$

The system has only one rule of inference, namely, ($\imp-$):

($\imp-$):
$$
\frac{\ph\,,\,\ph\imp\psi}{\psi}
$$

Proof systems of this simple sort, in which proofs are represented by finite sequences of sentences rather than arguments, are sometimes referred to as Hilbert-style proof systems, in honor of the mathematician David Hilbert, who was among the first logicians to propose their study.\footnote{The specific Hilbert-style proof system for propositional logic referred to here as $\Hp$ was first introduced by the Polish logician Jan \L ukasiewicz.} While Hilbert-style proof systems are simpler in structure than the systems for natural deduction that we have been considering so far, this structural simplicity comes at a cost.
With only a single direct rule of inference at our disposal, proofs in the system are much more difficult to construct.
Consider, for example, the claim $\proves\ph\imp\ph$.
In the natural deduction system $\p$, this claim is trivial, however, in the Hilbert-style deductive system $\Hp$ this claim is not so easy to establish:

:::{#thm-reflexivity-Hp .theorem}
$\proveshp\ph\imp\ph$
:::

:::{.lproof}
    1.  \varphi\rightarrow((\psi\rightarrow\varphi)\rightarrow\varphi)  [P$1$]
    2.  (\varphi\rightarrow((\psi\rightarrow\varphi)\rightarrow\varphi))\rightarrow((\varphi\rightarrow(\psi\rightarrow\varphi))\rightarrow(\varphi\rightarrow\varphi)) [P$2$]
    3.  (\varphi\rightarrow(\psi\rightarrow\varphi))\rightarrow(\varphi\rightarrow\varphi)  [$\rightarrow-$: 1, 2]
    4.  \varphi\rightarrow(\psi\rightarrow\varphi)          [P$1$]
    5.  \varphi\rightarrow\varphi                           [$\rightarrow-$: 4, 3]
:::

:::{#exr-derive-Hp .exercise}
{{< include /exercises/derive-Hp.qmd >}}
:::

In the remainder of this section, we will show that the proof system $\Hp$ is, in fact, equivalent in deductive power to the system $\p^{-}$---and hence to the system $\p$.
To show this, we must establish that the rules of inference ($\imp$+), ($\neg$-), and ($\neg$+) are all derivable in $\Hp$.
We begin with the rule ($\imp$+).
In the context of a Hilbert-style proof system, the fact that this rule holds is referred to as the 'deduction theorem':

:::{#thm-deduction-theorem .theorem}
If $\Ga,\ph\proveshp\psi$, then $\Ga\proveshp\ph\imp\psi$.

:::{.proof}
Let $\ph_1,\ldots,\ph_n$ be a proof of $\psi$ from $\Gamma\cup\{\ph\}$ in $\Hp$.
Since $\psi=\ph_n$, to prove that $\Gamma\proveshp \ph\imp\psi$ it will suffice to show that for all $i=1,\ldots,n$: $\Gamma\proveshp\ph\imp\ph_i$.

We prove this claim by induction on $i$.
We first note that since $\ph_i$ appears in a proof of $\psi$ from $\Ga\cup\{\ph\}$, either: (i) $\ph_i\in\Gamma$; (ii) $\ph_i=\ph$; (iii) $\ph_i$ is an axiom of $\Hp$; or (iv) $\ph_i$ results from applying the rule ($\imp$-) to previous lines in the proof.
In cases (i) and (iii), we have $\Gamma\proveshp\ph\imp\ph_i$ by the following proof:

:::{.lproof}
    1.  \varphi_{i}\rightarrow(\varphi\rightarrow\varphi_{i})    [P$1$]
    2.  \varphi_{i}                                              [Premise or Axiom]
    3.  \varphi\rightarrow\varphi_{i}                            [$\rightarrow-$: 1, 2] 
:::

Here, the inclusion of $\ph_i$ in the second step of the proof is justified on the grounds of its being either a premise or an axiom, depending on the case under consideration.
In case (ii), $\Gamma\proveshp\ph\imp\ph_i$ follows from @thm-reflexivity-Hp.
For case (iv), suppose that $\ph_i$ is the result of applying ($\imp$-) to $\ph_j$ and $\ph_k=\ph_j\imp\ph_i$, where $j,k<i$.
By the induction hypothesis, we have:

1. $\Gamma\proveshp\ph\imp\ph_{j}$

2. $\Gamma\proveshp\ph\imp(\ph_{j}\imp\ph_i)$

The proof of $\ph\imp\ph_i$ from $\Ga$ is as follows:

:::{.lproof}
    1.  (\varphi\rightarrow(\varphi_{j}\rightarrow\varphi_{i}))\rightarrow((\varphi\rightarrow\varphi_{j})\rightarrow(\varphi\rightarrow\varphi_{i})) [P2]
    2. \varphi\rightarrow(\varphi_{j}\rightarrow\varphi_{i})                    [by (2) above]
    3. (\varphi\rightarrow\varphi_{j})\rightarrow(\varphi\rightarrow\varphi_{i}) [$\rightarrow-$: 1, 2]
    4. \varphi\rightarrow\varphi_{j}                                            [by (1) above]
    5. \varphi\rightarrow\varphi_{i}                                            [$\rightarrow-$: 4, 3]
:::
This completes the induction.
:::
:::

The deduction theorem holds in any Hilbert-style proof system for $\Lp$ which has P$1$ and P$2$ as axiom schemas and ($\imp$-) as its only rule of inference.
Indeed, the principal reason for including these axiom schemas in our system is to facilitate the proof of this theorem, which is very useful for establishing claims about provability in $\Hp$.
For example, the following two derived rules of inference, which will be useful in the sequel, are straightforward consequencs of the deduction theorem:

:::{#thm-transitivity-hp .theorem}
## Transitivity
$\ph\imp\psi, \psi\imp\chi\proveshp\ph\imp\chi$

:::{.proof}
By two applications of ($\imp-$), we have $\ph,\ph\imp\psi,\psi\imp\chi\proves_{\Hp}\chi$.
Hence, the desired result follows by the deduction theorem.
:::
:::

:::{#thm-transmission-hp .theorem}
## Transmission
$\ph\proveshp(\ph\imp\psi)\imp\psi$

:::{.proof}
By ($\imp-$), we have $\ph,\ph\imp\psi\proves_{\Hp}\psi$.
Hence, the desired result follows by the deduction theorem.
:::
:::

The significance of the axiom schema P$3$ can be best understood by considering the role that it plays in deriving the rules ($\neg$-) and ($\neg$+) in $\Hp$.
Let us begin with the rule ($\neg$-), which asserts that if $\Ga\proves\neg\neg\ph$, then $\Ga\proves\ph$.
The following theorem suffices to show that this rule is valid in $\Hp$:

:::{#thm-double-negation .theorem}
$\neg\neg\ph\proveshp\ph$

:::{.proof}
Let $\psi$ be any axiom of $\Hp$.
Then, the following is a proof of $\ph$ from $\neg\neg\ph$ in $\Hp$:

:::{.lproof}
    1.  \psi                                             [Axiom]
    2.  (\neg\neg\psi\rightarrow\neg\neg\varphi)\rightarrow(\neg\varphi\rightarrow\neg\psi) [P$3$]
    3.  (\neg\varphi\rightarrow\neg\psi)\rightarrow(\psi\rightarrow\varphi)                 [P$3$]
    4.  (\neg\neg\psi\rightarrow\neg\neg\varphi)\rightarrow(\psi\rightarrow\varphi)         [Transitivity: 2, 3]
    5.  \neg\neg\varphi\rightarrow(\neg\neg\psi\rightarrow\neg\neg\varphi)              [P$1$]
    6.  \neg\neg\varphi\rightarrow(\psi\rightarrow\varphi)                              [Transitivity: 5, 4]
    7.  (\neg\neg\varphi\rightarrow(\psi\rightarrow\varphi))\rightarrow((\neg\neg\varphi\rightarrow\psi)\rightarrow(\neg\neg\varphi\rightarrow\varphi))     [P$2$]
    8.  (\neg\neg\varphi\rightarrow\psi)\rightarrow(\neg\neg\varphi\rightarrow\varphi)  [$\rightarrow-$: 6, 7]
    9.  \psi\rightarrow(\neg\neg\varphi\rightarrow\psi)                     [P$1$]
    10. \neg\neg\varphi\rightarrow\psi                                      [$\rightarrow-$: 1, 9]
    11. \neg\neg\varphi\rightarrow\varphi                                   [$\rightarrow-$: 8, 10]
    12. \neg\neg\varphi                                                     [Premise]
    13. \varphi                                                             [$\rightarrow-$: 11, 12]
:::
:::
:::

It only remains to show that the hypothetical rule of inference ($\neg$+) is valid in $\Hp$.
This fact is stated in @thm-reductio-Hp, the proof of which makes use of the following three claims:

:::{#thm-contraposition-Hp .theorem}
$\ph\imp\neg\psi\proveshp\psi\imp\neg\ph$

:::{.proof}
By transitivity, we have $\neg\neg\ph\imp\ph,\ph\imp\neg\psi\proveshp\neg\neg\ph\imp\neg\psi$.
But, by P3 and ($\rightarrow-$), $\neg\neg\ph\imp\neg\psi\proveshp\psi\imp\neg\ph$.
Hence, $\neg\neg\ph\imp\ph,\ph\imp\neg\psi\proveshp\psi\imp\neg\ph$.
But, by @thm-double-negation and the deduction theorem, it follows that $\proveshp\neg\neg\ph\imp\ph$.
Hence, $\ph\imp\neg\psi\proveshp\psi\imp\neg\ph$.
:::
:::

:::{#thm-dn-intro .theorem}
$\proveshp(\ph\imp\psi)\imp(\neg\neg\ph\imp\psi)$

:::{.proof}
By transitivity, we have $\neg\neg\ph\imp\ph, \ph\imp\psi\proveshp\neg\neg\ph\imp\psi$.
Hence, by the deduction theorem, $\neg\neg\ph\imp\ph\proveshp(\ph\imp\psi)\imp(\neg\neg\ph\imp\psi)$.
But, by @thm-double-negation and the deduction theorem, it follows that $\proveshp\neg\neg\ph\imp\ph$.
Hence, $\proveshp(\ph\imp\psi)\imp(\neg\neg\ph\imp\psi)$.
:::
:::

:::{#thm-clavius .theorem}
$\ph\imp\neg\ph\proveshp\neg\ph$

:::{.proof}
By @thm-double-negation and ($\imp-$), we have $\neg\neg\ph, \ph\imp\psi\proves\psi$.
Hence, by the deduction theorem, we have $\proveshp(\ph\imp\psi)\imp(\neg\neg\ph\imp\psi)$.
We will take this as given in our proof below.
Let $\psi$ be any axiom of $\Hp$.
Then, the followig is a proof of $\ph$ from $\ph\imp\neg\ph$ in $\Hp$:

:::{.lproof}
    1.  \neg\neg\varphi\rightarrow(\neg\neg\psi\rightarrow\neg\neg\varphi)  [P$1$]
    2.  (\neg\neg\psi\rightarrow\neg\neg\varphi)\rightarrow(\neg\varphi\rightarrow\neg\psi) [P$3$]
    3.  \neg\neg\varphi\rightarrow(\neg\varphi\rightarrow\neg\psi)          [Transitivity: 1, 2]
    4.  (\neg\neg\varphi\rightarrow(\neg\varphi\rightarrow\neg\psi))\rightarrow((\neg\neg\varphi\rightarrow\neg\varphi)\rightarrow(\neg\neg\varphi\rightarrow\neg\psi)) [P$2$]
    5.  (\neg\neg\varphi\rightarrow\neg\varphi)\rightarrow(\neg\neg\varphi\rightarrow\neg\psi) [$\rightarrow-$: 3, 4]
    6.  (\neg\neg\varphi\rightarrow\neg\psi)\rightarrow(\psi\rightarrow\neg\varphi)     [P$3$]
    7.  (\neg\neg\varphi\rightarrow\neg\varphi)\rightarrow(\psi\rightarrow\neg\varphi)  [Transitivity: 5, 6]
    8. \psi               [Axiom]
    9. (\psi\rightarrow\neg\varphi)\rightarrow\neg\varphi               [Transmission: 8]
    10.  (\neg\neg\varphi\rightarrow\neg\varphi)\rightarrow\neg\varphi  [Transitivity: 7, 9]
    11.  (\varphi\rightarrow\neg\varphi)\rightarrow(\neg\neg\varphi\rightarrow\neg\varphi)  [@thm-dn-intro]
    12. (\varphi\rightarrow\neg\varphi)\rightarrow\neg\varphi           [Transitivity: 11, 10]
    13. \varphi\rightarrow\neg\varphi                                   [Premise]
    14. \neg\varphi                                                     [$\rightarrow-$: 12, 13]
:::
:::
:::

:::{#thm-reductio-Hp .theorem}
If $\Ga,\ph\proveshp\psi$ and $\Ga,\ph\proveshp\neg\psi$, then $\Ga\proveshp\neg\ph$.

:::{.proof}
By the deduction theorem, we have both $\Ga\proveshp\ph\imp\psi$ and $\Ga\proveshp\ph\imp\neg\psi$.
By @thm-contraposition-Hp, it follows from the latter that $\Ga\proveshp\psi\imp\neg\ph$.
Hence, by transitivity, $\Ga\proveshp\ph\imp\neg\ph$, which, by @thm-clavius, implies $\Ga\proveshp\neg\ph$.
:::
:::

Thus, it turns out that the deductive system $\Hp$ is no less powerful than the deductive system $\p^{-}$, and hence no less powerful than $\p$.
If needed, we can therefore utilize the full machinery of natural deduction in $\p$ to establish claims about provability in $\Hp$.

## The Soundness and Completeness of $\p$ {#sec-propositional-logic-the-soundness-and-completeness-of}

In this section, we will establish the soundness and completeness of the proof system $\p$ with respect to the truth-functional semantics for propositional logic.
Since the proof system $\p$ is deductively equivalent to the Hilbert-style proof system $\Hp$, it will suffice to establish soundness and completeness for this latter system: $\Ga\proveshp\ph$ iff $\Ga\models\ph$.

### The Soundness of $\Hp$

To show that the system $\Hp$ is sound, it suffices to show that every axiom of $\Hp$ is a logical truth, and that every rule of inference corresponds to a valid argument.
That every axiom is a logical truth can be easily verified by means of truth-tables for the axioms schemas P$1$-P$3$.
For example, that every instance of the schema P$1$ is a logical truth can be confirmed as follows:

|  $\ph$   |  $\psi$  | $\psi\imp\ph$ | $\ph\imp(\psi\imp\ph)$ |
| :------: | :------: | :-----------: | :--------------------: |
| $\true$  | $\true$  |    $\true$    |        $\true$         |
| $\true$  | $\false$ |    $\true$    |        $\true$         |
| $\false$ | $\true$  |   $\false$    |        $\true$         |
| $\false$ | $\false$ |    $\true$    |        $\true$         |

We leave it to the reader to supply the corresponding truth tables for the axiom schemas P$2$ and P$3$ confirming that each of their instances is a logical truth.

To show that ($\imp-$) corresponds to a valid argument, we must show that $\ph,\ph\imp\psi\models\psi$.
Let $\si$ be an interpretation such that $val^\si(\ph)=\true$ and $val^\si(\ph\imp\psi)=\true$.
Then:
$$
val^\si(\ph\imp\psi)=f_\imp(val^\si(\ph),val^\si(\psi)) = f_\imp(\true, val^\si(\psi)) = \true
$$
But then, by the definition of $f_\imp$ it follows that $val^\si(\psi)=\true$.

Note that the soundness of $\Hp$ expresses a fact about what is _not_ provable in the system.
In particular, it asserts that no claim which does not logically follow from $\Gamma$ is provable from $\Gamma$ in the system.
In establishing the soundness of $\Hp$, the strategy we employed was to show that the property of truth under a given interpretation is possessed by any sentence provable from any set of sentences all of which possess this property.
Since it follows from the definition of validity, that if $\Gamma\not\models \ph$, there is some interpretation such that truth under this interpretation is not preserved in passing from $\Gamma$ to $\ph$, it can be inferred that $\Gamma\not\proveshp \ph$.

As a general rule, we may note that any property possessed by the axioms of a deductive system and which is preserved under its rules of inference, is possessed by every theorem of that system.
This fact can be used to show that certain sentences are not theorems.
For example, consider the deductive system which has axiom schemas P$$1$ and P$2$ and ($\imp-$) as its sole rule of inference, and let $f_\false$ be the unary truth function which always returns the truth value $\false$.
If we replace the semantical rule (S2), with the ''non-standard'' semantical rule:

(S2)$^*$: For any sentence $\ph$:
$$
val^\si(\neg\ph) = f_{\false}(val^\si(\ph))
$$

it can easily be verified that every instance of P$1$ and P$2$ has the property of being true under all interpretations of the language, and that this property is preserved under applications of the rule ($\imp-$).
Hence, every theorem of this system must likewise possesses this property.
Note, however, that if $\psi$ is true and $\ph$ is false the sentence $(\neg\ph\imp\neg\psi)\imp(\psi\imp\ph)$ is false, and so provided $\psi$ is a sentence which can be true and $\ph$ a sentence which can be false, this sentence cannot be proven in the system.
Since, however, this sentence is a logical truth (with respect to the standard semantics for propositional logic), it follows that the proof system consisting of just P1, P2, and the rule ($\cond-$) is incomplete.

:::{#exr-incomplete-fragments-P .exercise}
{{< include /exercises/incomplete-fragments-P.qmd >}}
:::

### The Completeness of $\Hp$

In this section we will prove the completeness of $\Hp$.
Our proof of completeness will employ the same technique that we employed in establishing the completeness of the proof system $\s$ for syllogistic logic described in Chapter 2.
First, we will show that the completeness theorem is equivalent to the claim that every consistent set of sentences is satisfiable.

:::{#def-p-satisfiability .definition}
Let $\Gamma$ be any set of sentences.
We say that $\Gamma$ is _satisfiable_ iff there exists an intepretation $\si$, such that $val^\si(\ph)=\true$, for all $\ph\in\Gamma$.
We say that $\Gamma$ is _unsatisfiable_ if it is not satisfiable.
:::

:::{#def-p-consistency .definition} 
Let $\Gamma$ be any set of sentences.
We say that $\Gamma$ is _consistent_ iff there is no sentence $\ph$, such that $\Gamma\proveshp\ph$, and $\Gamma\proveshp\neg\ph$.
We say that $\Gamma$ is _inconsistent_ if it is not consistent.
:::

If $\Hp$ is complete, then every consistent set of sentences is satisfiable.
To see this, let $\Gamma$ be unsatisfiable.
Since there is no interpretation which satisfies $\Gamma$, it follows trivially that for every $\ph$, both $\Gamma\models \ph$ and $\Gamma \models \neg\ph$.
Thus, if the system is complete, both $\Gamma\proveshp\ph$ and $\Gamma\proveshp\neg\ph$, i.e., $\Gamma$ is inconsistent.
The converse of this claim holds as well, that is, if every consistent set of sentences is satisfiable, then the system $\Hp$ is complete.
We begin by observing the following two facts:

:::{#thm-p-sat .theorem}
$\Gamma\not\models \ph$ iff $\Gamma\cup\{\neg\ph\}$ is satisfiable.

:::{.proof}
$\Gamma\cup\{\neg\ph\}$ is satisfiable iff there exists an interpretation $\si$, such that $val^\si(\psi)=\true$, for all $\psi\in\Ga\cup\{\neg\ph\}$.
But this is true iff there exists an intepretation $\si$, such that $val^\si(\psi)=\true$, for all $\psi\in\Ga$, and $val^\si(\ph)=\false$, i.e., $\Gamma\not\models \ph$.
:::
:::

:::{#thm-p-con .theorem}
$\Gamma\not\proveshp\ph$ iff $\Gamma\cup\{\neg\ph\}$ is consistent.

:::{.proof}
First, suppose that $\Ga\proveshp\ph$.
Then, $\Ga,\neg\ph\proveshp\ph$ and $\Gamma,\neg\ph\proveshp\neg\ph$, and so $\Gamma\cup\{\neg\ph\}$ is inconsistent.
Next, suppose that $\Gamma\cup\{\neg\ph\}$ is inconsistent.
Then there exists a sentence $\psi$ such that $\Gamma, \neg\ph\proveshp\psi$ and $\Gamma,\neg\ph\proveshp\neg\psi$.
By ($\neg+$), we have $\Ga\proveshp\neg\neg\ph$.
Hence, by ($\neg-$), $\Ga\proveshp\ph$.
:::
:::

In its contrapositive form, the completeness theorem asserts that if $\Gamma\not\proveshp\ph$, then $\Gamma\not\models \ph$.
Thus, from @thm-p-sat and @thm-p-con, completeness is equivalent to the following claim: if $\Gamma\cup\{\neg\ph\}$ is consistent, then $\Gamma\cup\{\neg\ph\}$ is satisfiable.
Hence, if every consistent set of sentences is satisfiable, the completeness theorem holds.
All told, then, the completeness theorem may be reformulated as the claim that every consistent set of sentences is satisfiable.

To show that the completeness theorem holds, we will construct, for any given consistent set of sentences, an interpretation which satisfies this set.
Our construction will proceed as follows: we will consider the sentences of the language, one by one, and determine, for each such sentence, whether or not it can be consistently added to the sentences already in the set.
If so, we will add it to the set, if not, we will add its negation to the set.
In this way, we will extend the original set to a 'maximal' set of sentences which can be used to decide, in a consistent manner, the truth or falsity of every sentence in the language.

As we shall see, such a maximally consistent set amounts to an explicit characterization of a truth valuation of the language, with the members of the set indicating which of the sentences are true under this valuation.
By considering which of the atomic sentences belong to this set, we will be able to arrive at an interpretation of the language that satisfies every sentence in the maximal set.
Since the original set is contained in this maximal set, it too will be satisfied by this interpretation.

For convenience, we collect together in the following theorem all the relevant facts about provability in $\Hp$ that we will have occasion to appeal to in our proof of completeness:

:::{#thm-p-proof-facts .theorem}
For any sentences $\ph$ and $\psi$:

i. $\neg\neg\ph\proveshp\ph$

ii. $\ph, \neg\psi\proveshp\neg(\ph\imp\psi)$

iii. $\neg\ph\proveshp\ph\imp\psi$

iv. $\ph\proveshp\psi\imp\ph$

:::

:::{#def-p-max-con .definition} 
A set of sentences $\Gamma$ is _maximally consistent_ if the following two conditions hold:

1. $\Gamma$ is consistent.

2. For every sentence $\ph$: if $\ph\not\in\Ga$, then $\Ga\cup\{\ph\}$ is  inconsistent.
:::

:::{#thm-p-con-addition .theorem}
If $\Gamma$ is a consistent set of sentences, then, for any sentence $\ph$, either $\Gamma\cup\{\ph\}$ or $\Gamma\cup\{\neg\ph\}$ is consistent.

:::{.proof}
Suppose, for contradiction, that both $\Gamma\cup\{\ph\}$ and $\Gamma\cup\{\neg\ph\}$ are inconsistent.
If $\Gamma\cup\{\ph\}$ is inconsistent, then, by @thm-p-proof-facts.(i), $\Gamma\cup\{\neg\neg\ph\}$ is inconsistent.
Hence, by @thm-p-con, $\Gamma\proveshp\neg\ph$.
But, if $\Gamma\cup\{\neg\ph\}$ is inconsistent, then, again by @thm-p-con, $\Gamma\proveshp\ph$.
This, however, contradicts the assumption that $\Gamma$ is consistent.
:::
:::

:::{#thm-p-max-con .theorem}
If $\Gamma$ is a maximally consistent set of sentences, then, for every sentence $\ph$, exactly one sentence in the set $\{\ph, \neg\ph\}$ is a member of $\Gamma$.

:::{.proof}
That at most one of these two sentences belongs to $\Gamma$ follows from the fact that $\Gamma$ is consistent.
Now, suppose that both $\ph\not\in\Gamma$ and $\neg\ph\not\in\Ga$.
By the definition of maximal consistency, both $\Gamma\cup\{\ph\}$ and $\Ga\cup\{\neg\ph\}$ are inconsistent.
But, by @thm-p-con-addition, it follows that $\Ga$ is inconsistent, which contradicts the assumption that $\Gamma$ is maximally consistent.
:::
:::

:::{#thm-p-max-con-sat .theorem}
Every maximally consistent set of sentences is satisfiable

:::{.proof}
Let $\Gamma$ be a maximally consistent set of sentences, and let $\si_\Ga$ be the interpretation defined by:
$$
    \si_\Ga(\p_i)=\left\{\begin{array}{ll} \true & \textrm{ if }\p_i\in\Gamma     \\
             \false     & \textrm{ if }\neg\p_i\in\Gamma\end{array}\right.
$$

By @thm-p-max-con, this is a well-defined interpretation of $\Lp$.
Thus, it will suffice to show that $\Ga$ is satisfiable to show that $val^{\si_\Ga}(\ph)=\true$ iff $\ph\in\Gamma$.
The proof will proceed by induction on the sentences.
If $\ph$ is an atomic sentence, then the claim follows directly from the definition of $\si_\Ga$.

Now, suppose that $\neg\ph\in\Gamma$.
Then, by @thm-p-max-con, $\ph\not\in\Ga$, and so, by the induction hypothesis, $val^{\si_\Ga}(\ph)=\false$.
Hence, $val^{\si_\Ga}(\neg\ph)=\true$.
If, on the other hand, $\neg\ph\not\in\Gamma$, then, by @thm-p-max-con, $\ph\in\Gamma$, and so, by the induction hypothesis, $val^{\si_\Ga}(\ph)=\true$.
Hence $val^{\si_\Ga}(\neg\ph)=\false$.
So, $\neg\ph\in\Ga$ iff $val^{\si_\Ga}(\neg\ph)=\true$.

Next, suppose that $\ph\imp\psi\in\Gamma$.
Then, either $\ph\not\in\Gamma$ or $\psi\in\Gamma$.
For if neither is the case, then, by Theorem @thm-p-max-con, both $\ph\in\Ga$ and $\neg\psi\in\Ga$, and so $\Ga\proveshp\ph$ and $\Ga\proveshp\neg\psi$.
But then, by @thm-p-proof-facts.(ii), $\Ga\proveshp\neg(\ph\imp\psi)$, which contradicts the assumption that $\Ga$ is consistent.
So, either $\ph\not\in\Gamma$ or $\psi\in\Ga$.
If, on the one hand, $\ph\not\in\Ga$, then, by the induction hypothesis, $val^\si_\Ga(\ph)=\false$, from which it follows that $val^\si_\Ga(\ph\imp\psi)=\true$.
If, on the other hand, $\psi\in\Ga$, then, by the induction hypothesis, $val^\si_\Ga(\ph)=\true$, from which it follows that $val^{\si_\Ga}(\ph\imp\psi)=\true$.
Hence, in either case, $val^{\si_\Ga}(\ph\imp\psi)=\true$.

Lastly, suppose that $\ph\imp\psi\not\in\Ga$.
Then, by @thm-p-max-con, $\neg(\ph\imp\psi)\in\Ga$.
It follows that both $\ph\in\Ga$ and $\psi\not\in\Ga$.
For, if, on the one hand, $\ph\not\in\Ga$, then $\neg\ph\in\Ga$, and so $\Ga\proveshp\neg\ph$.
But, by @thm-p-proof-facts.(iii), $\Ga\proveshp\ph\imp\psi$, which contradicts the assumption that $\Ga$ is consistent.
If, on the other hand, $\psi\in\Ga$, then $\Ga\proveshp\psi$.
But, by @thm-p-proof-facts.(iv), $\Ga\proveshp\ph\imp\psi$, which again contradicts the assumption that $\Ga$ is consistent.
So, both $\ph\in\Ga$ and $\psi\not\in\Ga$.
By the induction hypothesis, we have $val^{\si_\Ga}(\ph)=\true$ and $val^{\si_\Ga}(\psi)=\false$, from which it follows that $val^{\si_\Ga}(\ph\imp\psi)=\false$.
All told, then, $\ph\imp\psi\in\Ga$ iff $val^{\si_\Ga}(\ph\imp\psi)=\true$.
This completes the induction.

:::
:::

Since every maximally consistent set of sentences is consistent, it only remains to show that every consistent set of sentences can be extended to a maximally consistent set.

:::{#thm-p-extension}
If $\Gamma$ is a consistent set of sentences, then there exists a maximally consistent set of sentences $\Gamma^*$ such that $\Gamma\subset\Gamma^*$.

:::{.proof}
Let $\ph_1,\ph_2,\ldots$ be an enumeration of all of the sentences of $\Lp$.
We construct an increasing sequence of sets $\Gamma_1\subset\Gamma_2\subset\ldots$ as follows: first, let $\Gamma_1=\Gamma$.
Now, suppose that $\Gamma_n$ ($n\geq 1$) has been constructed and that it is consistent.
Then let:
$$
\Gamma_{n+1}=\left\{\begin{array}{ll} \Gamma_n\cup\{\ph_n\} & \textrm{ if }\Gamma_n\cup\{\ph_n\}
             \textrm{ is consistent.}                                        \\
             \Gamma_n\cup\{\neg\ph_n\}  & \textrm{otherwise}\end{array}\right.
$$
By @thm-p-con-addition, $\Gamma_{n+1}$ is consistent, and so the construction can continue.
Let $\Gamma^*$ be the set of all sentences which appear in some set in the sequence $\Ga_1,\Ga_2,\ldots$.
Since $\Ga=\Ga_1$, clearly $\Ga\subset \Ga^*$.
We will now show that $\Gamma^*$ is a maximally consistent set.
Suppose, for contradiction, that $\Gamma^*$ is inconsistent.
Then for some $\ph$, $\Gamma^*\proveshp\ph$ and $\Gamma^*\proveshp\neg\ph$.
Given a proof of $\ph$ from $\Gamma^*$ and a proof of $\neg\ph$ from $\Gamma^*$, let $\Delta$ be the set of all sentences in $\Gamma^*$ that are appealed to as premises somewhere in this proof.
For each $\psi\in\Delta$, let $n(\psi)$ be the smallest $n$ such that $\psi\in\Gamma_n$.
Since proofs are, by definition, of finite length, $\Delta$ is a finite set.
Thus, the number $m=\max\{n(\psi):\psi\in\Delta\}$ is a finite number, and every sentence in $\Delta$ is a member of $\Gamma_m$.
But then the aforementioned proofs of $\ph$ and $\neg\ph$ from $\Ga^*$ are also proofs from $\Gamma_m$, and so $\Gamma_m$ is inconsistent.
But this contradicts the above definition of $\Gamma_m$.
Thus, $\Gamma^*$ is consistent.

Now, let $\ph$ be any sentence such that $\ph\not\in\Ga^*$.
By the definition of $\Gamma^*$, it follows that $\neg\ph\in\Ga^*$.
Hence, adding $\ph$ to $\Ga^*$ would render the set inconsistent.
Thus, $\Ga^*$ is a maximally consistent extension of $\Ga$.
:::
:::

The proof of the completeness of $\Hp$ now proceeds as follows.
Let $\Ga$ be any consistent set.
By @thm-p-extension, there exists a maximally consistent set $\Ga^*$ such that $\Ga\subset\Ga^*$.
As we have seen, $\Ga^*$ is satisfiable by the interpretation $\si_\Ga$.
But any interpretation that satisfies $\Gamma^*$ also satisfies $\Ga$, and so $\Ga$ too is satisfiable.

Hence, every consistent set of sentences is satisfiable, and this, as we have seen, is equivalent to the completeness of $\Hp$.
Thus, the proof system $\Hp$---and so, likewise, the system $\p$---is a sound and complete proof system with respect to the truth-functional semantics for propositional logic.

## References {#sec-propositional-logic-references-unnumbered .unnumbered}
